---
title: "Building models using the Gadget framework"
bibliography: [library.bib]
biblio-style: apalike
link-citations: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

# About this course

## Course objectives

This course is an introduction to using Gadget as an ecosystem simulator 
and stock assessment tool. It is introduced using Rgadget, an R library 
that simplifies and standardizes the procedure for creating the input model 
files needed for creating a Gadget model, as well as gather and visualize 
ouput files created by Gadget. Although input files can be created manually,
Rgadget facilitates reproducability and aids internal consistency of Gadget 
model creation by allowing Gadget models to be created, run, analyzed, and 
shared using a single set of R scripts. Please note, however, that both
Gadget and Rgadget are continuously being developed, so please remember to
update your installations frequently (1x / month). In addition, Rgadget is 
programmed using 'tidyverse', so a good understanding of how to program using 
tidyverse is a necessity. 

By the end of this course you should:

* correctly structure and format input files for building a simple Gadget
model and running a simulation via R using Rgadget
* become familiar enough with the various options in Gadget and how to implement
them using the Gadget User Guide that comes with the Gadget installation,
so that a more complex ecosystem can be simulated
* input data, generate likelihood components, and modify optimisation settings 
* understand the iterative reweighting procedure implemented in Rgadget
* become familiar with predefined figures and data frames generated by gadget.fit

## Your a priori homework

**Prior to the course** make sure your operating system is a unix derivative, 
such as linux or macosx, as the code and examples in this course is only tested 
against these operating systems. Windows should in theory work, but issues related 
to Windows line endings are known to cause random issues in Gadget. For those who do 
not want dual boot their computers they can install [VirtualBox](https://www.virtualbox.org/) 
and install linux on a virtual machine (you can find a selection of pre-install images 
[here](https://www.osboxes.org/virtualbox-images/) where it is recommended that you choose Ubuntu). 
However if you insist on using Windows you should install the `icesTAF` R-package to handle all the file conversion issues.  

To install Gadget follow the [installation guide](installing-gadget-from-source.html). 

Please also have the most recent version of [R](https://cran.r-project.org/) and [Rstudio](https://www.rstudio.com/) installed.

In addition, if you plan to run a simple model using your own data, please:

1. familiarize yourself with [tidyverse programming](introduction-to-tidyverse.html)

2. think about your model structure/ aggregation level and have R scripts ready that 
aggregate your data into an appropriately formatted data frame (i.e., columns of :
year, time step, area, age bins, length bins, or age- and length-bins - have a sneak
peak at our example model data [here](https://heima.hafro.is/~bthe/data_provided.zip))

3. know where to find the [Gadget User Guide](https://hafro.github.io/gadget2/userguide/chap-stock.html#sec:stockgrowth)


## Reading material

* [A model of cod in Icelandic waters](docs/ajms.pdf)
* [Two area cod - shrimp model](http://raunvisindastofnun.hi.is/sites/raunvisindastofnun.hi.is/files/rh-03-2011.pdf)
* [Uncertainty estimates with Gadget](docs/TAMS_Elvarsson.pdf)
* [MSE using ling in Icelandic waters](docs/elvarsson2018ling.pdf)
* [Cod - herring - sprat in the Baltic](docs/Kulatska_baltic_2018.pdf)
* [CAPAM talk on the Rgadget environment](http://capamresearch.org/sites/default/files/gadget_pre_Bjarki.pdf)
* [Length-based assessments](docs/lba.pdf)
* [Talk on ling MSE](docs/ling_pre.pdf)
* [Talk on preliminary shrimp model](docs/Icelandshrimp_PJW.pdf)
* [DST2: vol 2](https://www.hafogvatn.is/static/research/files/fjolrit-118.pdf)
* [DST2: vol 2](https://www.hafogvatn.is/static/research/files/fjolrit-119.pdf)
* Assessments that use Gadget:
  + [Ling in 5a](http://www.ices.dk/sites/pub/Publication%20Reports/Stock%20Annexes/2017/lin.27.5a_SA.pdf)
  + [Tusk in 5a and 14](http://www.ices.dk/sites/pub/Publication%20Reports/Stock%20Annexes/2017/lin.27.5a_SA.pdf)
  + [Golden redfish in 5, 6, 12 and 14](http://ices.dk/sites/pub/Publication%20Reports/Stock%20Annexes/2015/smr-5614_SA.pdf)
  + [Deep pelagic beaked redfish](http://ices.dk/sites/pub/Publication%20Reports/Stock%20Annexes/2015/smn-dp_SA.pdf) 
  + [Atlantic wolffish in Icelandic waters](https://www.hafogvatn.is/static/extras/images/09-AtlanticWolffish_TR%20(1)1141513.pdf)
  + [Greenland halibut in the Northeast Artic](http://ices.dk/sites/pub/Publication%20Reports/Stock%20Annexes/2015/ghl-arct_SA.pdf)
  + [Southern hake](http://www.ices.dk/sites/pub/Publication%20Reports/Stock%20Annexes/2017/hke-soth_SA.pdf)
* Source-code repository [on github](http://github.com/fishvice/gadget-models/)
 
